# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."gamevault-db" = {
    image = "postgres:17";
    environment = {
      "POSTGRES_DB" = "gamevault";
      "POSTGRES_PASSWORD" = "33e33e33e";
      "POSTGRES_USER" = "cig0073";
    };
    volumes = [
      "/var/lib/gamevault/postgresql:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=gamevault_default"
    ];
  };
  systemd.services."docker-gamevault-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-gamevault_default.service"
    ];
    requires = [
      "docker-network-gamevault_default.service"
    ];
    partOf = [
      "docker-compose-gamevault-root.target"
    ];
    wantedBy = [
      "docker-compose-gamevault-root.target"
    ];
  };
  virtualisation.oci-containers.containers."gamevault-gamevault-backend" = {
    image = "phalcode/gamevault-backend:latest";
    environment = {
      "DB_HOST" = "db";
      "DB_PASSWORD" = "33e33e33e";
      "DB_USERNAME" = "cig0073";
    };
    volumes = [
      "/var/lib/gamevault/games:/files:rw"
      "/var/lib/gamevault/media:/media:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gamevault-backend"
      "--network=gamevault_default"
    ];
  };
  systemd.services."docker-gamevault-gamevault-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-gamevault_default.service"
    ];
    requires = [
      "docker-network-gamevault_default.service"
    ];
    partOf = [
      "docker-compose-gamevault-root.target"
    ];
    wantedBy = [
      "docker-compose-gamevault-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-gamevault_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f gamevault_default";
    };
    script = ''
      docker network inspect gamevault_default || docker network create gamevault_default
    '';
    partOf = [ "docker-compose-gamevault-root.target" ];
    wantedBy = [ "docker-compose-gamevault-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-gamevault-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
